name: CI/CD to bump version automatically
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release Github
        id: generate-release
        if: github.run_attempt == 1
        uses: rymndhng/release-on-push-action@v0.23.1
        with:
          bump_version_scheme: minor
          tag_prefix: v
