name: CI/CD to bump go-commons version automatically
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Create GITHUB release
      uses: extenda/actions/conventional-release@v0
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}
