name: CI/CD to bump go-commons version automatically
on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: composite
  steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create GITHUB release
      uses: extenda/actions/conventional-release@v0
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
